info:
  title: Positive Group Admin Side
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: "2.0"
host: localhost:8000
basePath: /
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK